version: '3.3'
services:
  db:
    image: postgres:13.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - dev_db_folder:/var/lib/postgresql/data
volumes:
  dev_db_folder: